import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
 title: "Connect",
  description:"Connect a Social Art Platform for Creative Peoples to Showcase the Art",
  icons: {
    icon: "/logo.jpg",
  },
  authors: [
    {
      name: "Priyansh",
      url: "https://priyansh-port-folio.vercel.app/",
    },
  ],
  openGraph: {
    title: "Connect",
    description: "Generated by Astro Nova Labs",
    url: "https://your-website-url.com",
    type: "website",
    images: [
      {
        url: "/logo.jpg",
        width: 800,
        height: 600,
        alt: "Connect Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    site: "@yourtwitterhandle",
    creator: "@yourtwitterhandle",
    title: "Connect",
    description: "Generated by Priyansh",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="Connect, Astro Nova Labs, Priyansh, Portfolio, Web Development" />
        <meta name="theme-color" content="#ffffff" />
        <meta property="og:title" content="Connect" />
        <meta property="og:description" content="Generated by Astro Nova Labs" />
        <meta property="og:url" content="https://your-website-url.com" />
        <meta property="og:type" content="website" />
        <meta property="og:image" content="/logo.jpg" />
        <meta property="og:image:width" content="800" />
        <meta property="og:image:height" content="600" />
        <meta property="og:image:alt" content="Connect Logo" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@yourtwitterhandle" />
        <meta name="twitter:creator" content="@yourtwitterhandle" />
        <meta name="twitter:title" content="Connect" />
        <meta name="twitter:description" content="Generated by Astro Nova Labs" />
        <meta name="twitter:image" content="/logo.jpg" />
        <link rel="icon" href="/logo.jpg" />
        <title>Connect</title>
      </head>
      <body>{children}</body>
    </html>
  );
}
